// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: square.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSquareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetSquareRequest) Reset() {
	*x = GetSquareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSquareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSquareRequest) ProtoMessage() {}

func (x *GetSquareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSquareRequest.ProtoReflect.Descriptor instead.
func (*GetSquareRequest) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{0}
}

func (x *GetSquareRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetSquareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetSquareResponse) Reset() {
	*x = GetSquareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSquareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSquareResponse) ProtoMessage() {}

func (x *GetSquareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSquareResponse.ProtoReflect.Descriptor instead.
func (*GetSquareResponse) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{1}
}

func (x *GetSquareResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_square_proto protoreflect.FileDescriptor

var file_square_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32,
	0x4c, 0x0a, 0x06, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a,
	0x05, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_square_proto_rawDescOnce sync.Once
	file_square_proto_rawDescData = file_square_proto_rawDesc
)

func file_square_proto_rawDescGZIP() []byte {
	file_square_proto_rawDescOnce.Do(func() {
		file_square_proto_rawDescData = protoimpl.X.CompressGZIP(file_square_proto_rawDescData)
	})
	return file_square_proto_rawDescData
}

var file_square_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_square_proto_goTypes = []interface{}{
	(*GetSquareRequest)(nil),  // 0: square.GetSquareRequest
	(*GetSquareResponse)(nil), // 1: square.GetSquareResponse
}
var file_square_proto_depIdxs = []int32{
	0, // 0: square.Square.GetSquare:input_type -> square.GetSquareRequest
	1, // 1: square.Square.GetSquare:output_type -> square.GetSquareResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_square_proto_init() }
func file_square_proto_init() {
	if File_square_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_square_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSquareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_square_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSquareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_square_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_square_proto_goTypes,
		DependencyIndexes: file_square_proto_depIdxs,
		MessageInfos:      file_square_proto_msgTypes,
	}.Build()
	File_square_proto = out.File
	file_square_proto_rawDesc = nil
	file_square_proto_goTypes = nil
	file_square_proto_depIdxs = nil
}
